query pairHourDatas($skip: Int, $first: Int, $orderBy: PairDayData_orderBy, $orderDirection: OrderDirection, $where: PairDayData_filter, $skip1: Int, $first1: Int, $orderBy1: PairDayData_orderBy, $orderDirection1: OrderDirection, $where1: PairDayData_filter, $skip2: Int, $first2: Int, $orderBy2: PairHourData_orderBy, $orderDirection2: OrderDirection, $where2: PairHourData_filter, $block: Block_height){
    pairHourDatas(skip: $skip2, first: $first2, orderBy: $orderBy2, orderDirection: $orderDirection2, where: $where2, block: $block){
        id
        hourStartUnix
        pair{
            id
            token0{
                id
                symbol
                name
                decimals
                totalSupply
                tradeVolume
                tradeVolumeUSD
                untrackedVolumeUSD
                txCount
                totalLiquidity
                derivedETH
                mostLiquidPairs(skip: $skip1, first: $first1, orderBy: $orderBy1, orderDirection: $orderDirection1, where: $where1){
                    id
                    date
                    pairAddress
                    token0{
                        id
                        symbol
                        name
                        decimals
                        totalSupply
                        tradeVolume
                        tradeVolumeUSD
                        untrackedVolumeUSD
                        txCount
                        totalLiquidity
                        derivedETH
                    }
                    token1{
                        id
                        symbol
                        name
                        decimals
                        totalSupply
                        tradeVolume
                        tradeVolumeUSD
                        untrackedVolumeUSD
                        txCount
                        totalLiquidity
                        derivedETH
                        mostLiquidPairs(skip: $skip, first: $first, orderBy: $orderBy, orderDirection: $orderDirection, where: $where){
                            id
                            date
                            pairAddress
                            reserve0
                            reserve1
                            totalSupply
                            reserveUSD
                            dailyVolumeToken0
                            dailyVolumeToken1
                            dailyVolumeUSD
                            dailyTxns
                        }
                    }
                    reserve0
                    reserve1
                    totalSupply
                    reserveUSD
                    dailyVolumeToken0
                    dailyVolumeToken1
                    dailyVolumeUSD
                    dailyTxns
                }
            }
            token1{
                id
                symbol
                name
                decimals
                totalSupply
                tradeVolume
                tradeVolumeUSD
                untrackedVolumeUSD
                txCount
                totalLiquidity
                derivedETH
            }
            reserve0
            reserve1
            totalSupply
            reserveETH
            reserveUSD
            trackedReserveETH
            token0Price
            token1Price
            volumeToken0
            volumeToken1
            volumeUSD
            untrackedVolumeUSD
            txCount
            createdAtTimestamp
            createdAtBlockNumber
            liquidityProviderCount
        }
        reserve0
        reserve1
        reserveUSD
        hourlyVolumeToken0
        hourlyVolumeToken1
        hourlyVolumeUSD
        hourlyTxns
    }
}